name: pvc
type: source
endpoints:
  - name: sidea
    source:
      ip: 127.0.0.1
      port: 42002
    destination:
      ip: 127.0.0.1
      port: 42001
  - name: sideb
    source:
      ip: 127.0.0.1
      port: 42003
    destination:
      ip: 127.0.0.1
      port: 42004
