name: ubend
type: uturn
endpoints:
  - name: sidea
    source:
      ip: 127.0.0.1
      port: 42004
    destination:
      ip: 127.0.0.1
      port: 42003
  - name: sideb
    source:
      ip: 127.0.0.1
      port: 42005
    destination:
      ip: 127.0.0.1
      port: 42006
